"""empty message

Revision ID: 5348a5646751
Revises: d9c2159f42f9
Create Date: 2022-09-04 09:12:53.725913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5348a5646751'
down_revision = 'd9c2159f42f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attack_web',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('user_login', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attack_web')
    # ### end Alembic commands ###
